import {
    Laptop, Package, Megaphone, Briefcase, ShoppingCart,
    Truck, TrendingUp, Heart, Utensils, Hammer, GraduationCap, Camera
} from 'lucide-react';

export const ACTIVITIES_CATEGORIES = [
    {
        name: 'Technology & IT',
        icon: Laptop,
        color: 'from-blue-500 to-indigo-600',
        bestZones: ['Masdar City', 'IFZA', 'RAKEZ', 'SHAMS', 'SRTIP'],
        activities: [
            'Software Development',
            'Mobile App Development',
            'IT Consultancy',
            'Cybersecurity Services',
            'Cloud Computing Solutions',
            'Artificial Intelligence',
            'Web Design & Development',
            'SaaS Platform Provider',
            'Data Analytics',
            'Blockchain Development',
        ],
    },
    {
        name: 'Trading & Import/Export',
        icon: Package,
        color: 'from-amber-500 to-orange-600',
        bestZones: ['ANCFZ', 'RAKEZ', 'MEYDAN', 'DMCC', 'JAFZA'],
        activities: [
            'General Trading',
            'Electronics Trading',
            'Food & Beverage Trading',
            'Textile & Garments Trading',
            'Chemical Products Trading',
            'Machinery & Equipment Trading',
            'Wholesale Distribution',
            'Import & Export of Goods',
            'Commodity Trading',
            'Building Materials Trading',
        ],
    },
    {
        name: 'Media & Marketing',
        icon: Megaphone,
        color: 'from-pink-500 to-rose-600',
        bestZones: ['SHAMS', 'RAKEZ', 'IFZA', 'SRTIP', 'MEYDAN'],
        activities: [
            'Advertising Agency',
            'Digital Marketing',
            'Public Relations',
            'Content Creation & Production',
            'Social Media Management',
            'Influencer Marketing Agency',
            'Graphic Design Services',
            'Video Production',
            'Film & TV Production',
            'Print Media Publishing',
        ],
    },
    {
        name: 'Consulting & Professional Services',
        icon: Briefcase,
        color: 'from-slate-600 to-slate-800',
        bestZones: ['MEYDAN', 'RAKEZ', 'IFZA', 'SHAMS', 'RAK ICC'],
        activities: [
            'Business Management Consultancy',
            'HR & Recruitment Consultancy',
            'Legal Consultancy',
            'Financial Consultancy',
            'Tax Advisory',
            'Strategy & Planning Consultancy',
            'Project Management',
            'Engineering Consultancy',
            'Environmental Consultancy',
            'Training & Development',
        ],
    },
    {
        name: 'E-commerce & Retail',
        icon: ShoppingCart,
        color: 'from-emerald-500 to-teal-600',
        bestZones: ['ANCFZ', 'SPC', 'IFZA', 'RAKEZ', 'Dubai Commercial City'],
        activities: [
            'Online Retail Store',
            'Dropshipping Business',
            'Marketplace Seller',
            'B2B E-commerce Platform',
            'Subscription Box Service',
            'Digital Products Sales',
            'Print-on-Demand',
            'Wholesale E-commerce',
            'Fashion & Apparel Online Store',
            'Electronics Online Retail',
        ],
    },
    {
        name: 'Logistics & Freight',
        icon: Truck,
        color: 'from-yellow-500 to-amber-600',
        bestZones: ['JAFZA', 'Dubai South', 'RAKEZ', 'Ajman Free Zone', 'SRTIP',],
        activities: [
            'Freight Forwarding',
            'Cargo Shipping',
            'Supply Chain Management',
            'Warehousing & Storage',
            'Last-Mile Delivery',
            'Cold Chain Logistics',
            'Customs Clearance',
            'Courier Services',
            'Air Cargo Services',
            'Sea Freight Services',
        ],
    },
    {
        name: 'Finance & Investment',
        icon: TrendingUp,
        color: 'from-violet-500 to-purple-700',
        bestZones: ['MEYDAN', 'IFZA', 'DMCC', 'ADGM', 'RAKEZ'],
        activities: [
            'Investment Holding Company',
            'Family Office',
            'Financial Advisory',
            'Forex & Brokerage',
            'Crypto & Digital Assets',
            'Private Equity',
            'Venture Capital Fund',
            'Insurance Brokerage',
            'Wealth Management',
            'Payment Solutions Provider',
        ],
    },
    {
        name: 'Healthcare & Wellness',
        icon: Heart,
        color: 'from-red-500 to-rose-600',
        bestZones: ['DHCC', 'MEYDAN', 'IFZA', 'SHAMS', 'Sharjah Healthcare City'],
        activities: [
            'Medical Consultancy',
            'Pharmaceutical Trading',
            'Health & Wellness Coaching',
            'Telemedicine Platform',
            'Medical Equipment Trading',
            'Nutrition & Dietetics',
            'Fitness & Personal Training',
            'Mental Health Services',
            'Beauty & Cosmetics',
            'Spa & Wellness Centre',
        ],
    },
    {
        name: 'Food & Beverage',
        icon: Utensils,
        color: 'from-orange-500 to-red-500',
        bestZones: ['MEYDAN', 'Dubai South', 'IFZA', 'RAKEZ', 'ANCFZ'],
        activities: [
            'Food Trading & Distribution',
            'Food Manufacturing',
            'Restaurant & Catering',
            'Cloud Kitchen',
            'Beverage Manufacturing',
            'Food Import & Export',
            'Organic Food Supply',
            'Bakery & Confectionery',
            'Spices & Condiments Trading',
            'Food Consultancy',
        ],
    },
    {
        name: 'Construction & Real Estate',
        icon: Hammer,
        color: 'from-stone-500 to-stone-700',
        bestZones: ['MEYDAN', 'Dubai South', 'IFZA', 'RAKEZ', 'ANCFZ'],
        activities: [
            'Real Estate Development',
            'Property Management',
            'Interior Design',
            'Architecture Services',
            'Construction Contracting',
            'Civil Engineering',
            'MEP Services',
            'Landscaping Services',
            'Building Materials Supply',
            'Property Brokerage',
        ],
    },
    {
        name: 'Education & Training',
        icon: GraduationCap,
        color: 'from-cyan-500 to-blue-600',
        bestZones: ['MEYDAN', 'RAKEZ', 'Dubai South', 'IFZA', 'SPC', 'SRTIP'],
        activities: [
            'Online Education Platform',
            'Corporate Training',
            'Language School',
            'Tutoring Services',
            'Skills Development',
            'E-learning Content Creator',
            'Educational Consultancy',
            'Vocational Training Centre',
            'Coaching & Mentoring',
            'Exam Preparation Institute',
        ],
    },
    {
        name: 'Creative & Design',
        icon: Camera,
        color: 'from-fuchsia-500 to-pink-600',
        bestZones: ['SRTIP', 'SHAMS', 'RAKEZ', 'IFZA', 'ANCFZ'],
        activities: [
            'Photography Studio',
            'Videography Services',
            'Fashion Design',
            'Interior Decoration',
            'Product Design',
            'Animation & VFX',
            'Music Production',
            'Event Photography',
            'Brand Identity Design',
            'NFT & Digital Art',
        ],
    },
];
